---
title: "Presentation Technique"
---

:::{.callout-caution title="Under construction"}
:::

## First: Plan

The absolute first thing you need to understand about your talk, is **who** you will be talking to.

### Pitch (to investors):

1. Strong opening (a "Punch in the nose": PIN)
2. Need
3. Approach
4. Benefits at the given cost (cost/benefit ratio)
5. Competition (and why you’re better)
6. Financials (amount needed, use and returning how much by when)
7. Close with the ”The Ask” (Get to further discussion)

### Presenting PMx science

Slides:

1. Intro
2. Conclusion (pause for questions, to guide the rest of the presentation) **"tell ’em what you’re gonna tell ’em"**
3. Results (that support conclusion) **"tell ’em"**
4. Conclusion **"tell ’em what you told ’em"**
5. Many backup slides on details e.g., methods, demographic tables, graphics on study design, details on exclusion, PK sampling, etc.

## Second: Design

* Minimize text
* Max 5 bullet points per slide (if you use slides)
* *You* are the presentation, not the slide deck.
  * The focus of the audience should be on *you*
  * Use the ability to shut off the slide deck (turn screen black or white), when it is not needed.
* Focus the audience attention with clever use of blurr and colored boxes.
* If you need a laser pointer, your slide is probably too detailed/messy.
* Stick to a color theme.
  * Make the colors mean something across all slides.

## Third: Practice

### Practice your talk

* Go through your talk a couple of times.
  * Read it out loud, as you would in a real situation.
* If you want, record yourself and watch the recording.

### Go to the venue where you will talk.

* Where will you be?
* Will your slides be seen from the backmost row?
* Will you need a microphone?
* Will you need some other equipment, like an extension cord, some adapter?
* If you will be recorded, where can you move so you don't go out of picture?

* If presenting "offline", what projector will you be using, and how will the slides look like on that specific projector, in that specific room, at that specific time of the day (ie lighting conditions).

## Fourth: Deliver

### Right before

* Silence your phone.
* Go to the bathroom.

### During

* Talk to one person at a time, not the entire crowd.
  * Look him/her in the eyes, explain your point, then switch person.
* Trust yourself. The audience wants you too succeed, and they are interested in what you have to say.

## Fifth: Aftermath

* Seek feedback.
* Reflect on feedback.
* Share your talk online.
