---
title: "Self Management"
date: last-modified
---

:::{.callout-caution title="Under construction"}
:::

## Use the right metric

One reason some academic writers get lost is that they have been piling up words without knowing what they want to say or why they are saying it.
This often happens when word count or pages produced is our chosen productivity measure.
We academics can ramble on for pages, sounding profound without saying much of anything.
Good editors, and good readers, will call us on this.
So feeling lost can be a sign that we aren't writing thoughtfully even though we are meeting our goals for number of words or pages written.
Try shifting to a different productivity metric: time spent or points made or progress on through-line can serve as a measure for each session's progress.

## Productivity/effectiveness Tips ’n’ tricks

* Take regular breaks.
    * Use a variant of the pomodoro-method eg work in units of 45min focused work followed by 15min break.
* Plan only ~75% of your working time to allow for unforeseen things.
* Plan, then do, then re-evaluate your plan
* Schedule important things, and force yourself to stick to the schedule

5 % Strategy  
15 % Position  
80 % Action  

> Better to be in the arena getting stomped by the bull, than it is to be up in the stands, or out in the parking lot.

## Getting things done

* People have 100--200 next actions ar any one time
* Project: anything you are comited to finish within next few weeks/months that take more than one step to finish
* Most people have 30--100 projects
* Maintain vs Finish. Eg relationships, personal development

* Get your life back to widgets, but you have to define the widgets.
”Draft” instead of ”write” (crappy and still win)
* ”If you actually captured your thoughts the first time you had them, you’d be surprised how few you have”
* If you are not doing the Weekly Review, you are doing it all the time, but not really doing it.
Finish the thinking!
* Winston Churchill: Freedom from order.
Jock Willink: Discipline equals freedom.

## Project Square

Why

Scope (What) - Resources (money/people) (Who)  
Quality (How) - Time (When)

## Prioritization

* Risk matrix (Impact/probability)
* Priority matrix (Important/Urgent)
* SWOT/TOWS
* Focus on the *task*, not the solution
* Law of pi: everything takes at least 3.14 times longer than you think.
