---
title: "The Distribution Concept"
---

:::{.callout-caution title="Under construction"}
:::

The pharmacokinetic parameter that quantifies drug distribution, is called *volume of distribution* (V~d~).

In general, a lipophilic drug will have a large V~d~, and a hydrophilic drug will have a small V~d~.
Drugs can also be substrates to various transporters that impact V~d~.

![
  Reversible processes affecting the total amount of drug on each side of a biological membrane permeable only to the un-ionized free form of a drug.
  Some binding of both the un-ionized and ionized forms may occur, but depending on the specific drug, one form usually predominates (the un-ionized form is preferentially bound in the case of narcotic analgesics).
  Similarly, at active receptor sites, one form of the drug usually is effective and the other is not (a or b).
  A very high affinity of the drug for pharmacologically inactive binding sites in tissues or a large partitioning of a lipophillic drug into lipids creates a sink for drug accumulation in tissue and limits the free drug concentration, which determines the number of drug-receptor complexes formed and the intensity of drug action.
  Extensive binding and partitioning in tissue creates a large tissue distribution volume.
](images/distribution.png){#fig-distribution}

Typical physiological valoumes for a 70 kg adult:

* V~plasma~ ≈ 3 L
* V~interstitial~ ≈ 12 L
* V~water,extracellular~ ≈ 16 L
* V~cells~ ≈ 27 L
* V~water,total~ ≈ 42 L

## References

$$
\V=\V_{\mathrm{P}}+\V_{\mathrm{T}} \cdot \mathrm{~K}_{\mathrm{P}}
$$

$$
V = V_P + V_T \cdot \frac{f \hat{u}}{f u_T}
$$

$$
\Vd =
  \A_{\text{body}} / \Cpl
$$

$$
\Vdss = \A_\text{body, ss} / \Cplss
$$

$$
\Conc_\text{total} = \Conc_\text{unbound} + \Conc_\text{bound}
$$

$$
\fu = \Conc_\text{unbound} / \Conc_\text{total}
$$

$$
\fb = \Conc_\text{bound} / \Conc_\text{total}
$$

$$
\mathrm{k}_{\mathrm{p}}=\mathrm{C}_{\mathrm{T}} / \mathrm{C}_{\V}
$$

6. $\quad \mathrm{V}=\operatorname{Dose}_{\mathrm{iv}} / \mathrm{C}_{(0)}$
(1-compartment)
7. $\mathrm{V}_{\mathrm{ss}}=\mathrm{V}_{\mathrm{P}}+\mathrm{V}_{\mathrm{T}} \cdot f \mathrm{fu} / \mathrm{fu}_{\mathrm{T}}$
8. $\quad \mathrm{V}_{\text {app, } \mathrm{T}}=\mathrm{k}_{\mathrm{p}} \cdot \mathrm{V}_{\mathrm{T}}$
9. $\mathrm{V}_{\mathrm{ss}}=\mathrm{V}_{\mathrm{P}}+\Sigma \mathrm{V}_{\mathrm{app}, \mathrm{T}}$
(variation of eq. 7 \& 8)

::: {#refs}
:::
