---
title: "The Elimination Concept"
---

:::{.callout-caution title="Under construction"}
:::

The pharmacokinetic parameter that quantifies drug elimination, is called *clearance* (CL).

CL describes the relationship between concentration and the rate of elimination of drug from the body.
Note that elimination and clearance are NOT the same thing.

On a related note, the fact that CL is **made-up** and has no physical meaning is an important concept to understand.
CL is more a consequence of the underlying mathematics of pharmacokinetics than a real biological process.
A number of experimental observations in the late 1960s, early 1970s, could not be explained by the pharmacokinetic theory available at the time.
Researchers used concepts from the oil industry to explain the clearence of drug from the body.
What's more, CL is near impossible to interpret on its own, but somehow is still common to see in the summary of product characteristics for approved drugs.

A more intuitive parameter is the half-life (t~1/2~), which is the time it takes for the concentration of a drug to decrease by half.
However, even if the half-life is more intuitive, it is not very useful during the current state of modern drug developement.
The half-life of a drug is really only useful if a drug follows one-compartment PK with linear elimination, which is rare for modern drugs.

A better way to illustrate drug elimination, would be through typical PK predictions, and/or simulations.
In the therapeutic context of the drug, what elimination characteristics would be clinically useful to understand?
These characteristics can be quantified through deterministic predictions (no variability) or stochastic simulations (with variability).

## Hepatic CL (metabolism)

The liver can convert substances into metabolites.
This generally makes a more water soluble substance that can be excreted through the kidneys.

## Renal CL (excretion)

Kidney function is often checked using GFR (glomerular filtration rate) estimating equations.
These equations use endogenous biomarkers, like creatinine and cystatin C, along with age, sex, and weight, to estimate how well the kidneys work.

There are many equations for estimating GFR, some of these are designed for specific populations.
The estimated GFR from these equations are usually similar.
However, differences appear at high GFR levels, especially when the values go above 150 mL/min/1.73 m^2^, a condition called augmented renal clearance.

The most recommended equation right now is the 2021 version of the CKD-EPI formula [@inkerNewCreatinineCystatin2021]. This version does not consider race (@eq-ckd-epi-2021).

**CKD-EPI (2021) expressed as a single equation:**
$$
\text{eGFR} = 142 \times \text{min}(\frac{\text{Scr}}{K}, 1)^{\alpha} \times \text{max}(\frac{\text{Scr}}{K}, 1)^{-1.200} \times 0.9938^{\text{Age}} \times 1.012 [\text{if female}]
$$ {#eq-ckd-epi-2021}

| Abbreviations | Units | Description |
| :------------ | :--- | :--- |
| eGFR | mL/min/1.73 m^2^ | Estimated glomerular filtration rate |
| Scr  | mg/dL | Serum creatinine (standardized) |
| $K$ | | 0.7 (females) or 0.9 (males) |
| $\alpha$ | | -0.241 (females) or -0.302 (males) |
| min() | | indicates the minimum of $\frac{\text{Scr}}{K}$ or 1 |
| max() | | indicates the maximum of $\frac{\text{Scr}}{K}$ or 1 |

In general, if the serum creatinine rises at 2--3 mg/dl per day then the GFR is near zero.

## References


# Elimination

$$
\quad \CL=$ Rate of elimination $/ \mathrm{C}
$$

$$
\mathrm{E}=\CL_{\text {blood }} / \mathrm{Q}
$$

$$
\fe + \fm = 1
$$

$$
\quad \CL_{\text {plasma }} \times \mathrm{C}_{\text {plasma }}=\CL_{\text {blood }} \times \mathrm{C}_{\text {blood }}
$$

10. $\CL=$ Dose $_{\mathrm{iv}} / \mathrm{AUC}_{\mathrm{iv}, 0-\infty}$
(Intravenous case)
11. $\CL / \mathrm{F}=$ Dose $_{\text {extravascular }} / \mathrm{AUC}_{\text {extravascular }, 0-\infty}$
(Extravascular case, F unknown)
12. $\CL=\CL_{\mathrm{H}}+\CL_{\mathrm{R}}+\CL_{\text {other }}$
13. $\CL_{\mathrm{H}}=\CL_{\mathrm{H}, \text { met }}+\CL_{\text {biliary }}$
14. $\quad \CL_{\mathrm{H}, \text { blood }}=\frac{\mathrm{Q}_{\mathrm{H}} \times \mathrm{f}_{\mathrm{u} \text {,blood }} \times \CL_{\text {int }}}{\mathrm{Q}_{\mathrm{H}}+\mathrm{f}_{\mathrm{u}, \text { blood }} \times \CL_{\text {int }}}$
15. $\quad \CL_{\mathrm{int}}=\sum_1^{\mathrm{i}} \frac{\mathrm{V}_{\mathrm{m}, \mathrm{i}}}{\mathrm{K}_{\mathrm{m}, \mathrm{i}}+\mathrm{C}_{\mathrm{u}}}$
16. $\quad \CL_{\mathrm{R}}=\left[\CL_{\text {filtr }}+\CL_{\text {secr }}\right] \times\left(1-\mathrm{f}_{\text {reabs }}\right)$
17. $\CL_{\text {filtr }}=\mathrm{f}_{\mathrm{u}} \times \mathrm{GFR}$
18. Rate of excretion $=d A e / d t=($ Rate of filtration + Rate of secretion $) \times\left(1-f_{\text {reabs }}\right)=C L_R \times C$
19. $f_e=A_e /$ Dose $_{i v}=$ CL $_R / C L$

## Elimination rate (1-compartment case)

$$
t_\textonehalf = \frac{\ln 2}{\ke}
$$

$$
\ke = \CL / \V
$$

$$
\C = \C_0 \times \mathrm{e}^{-\mathrm{k} \times \mathrm{t}}
$$

$$
\mathrm{t} = \ln \left(\Conc_0 / \Conc \right) / \mathrm{k}
$$

$$
\CL = \frac{\text { Dose }}{\AUC}
$$

$$
\CL = k_e \times V_d
$$

## Metabolic and Renal Clearance

$$
\mathrm{E}_{\mathrm{H}}=\frac{C l_{\mathrm{int}} \times f u_b}{Q_H+C l_{\mathrm{int}} \times f u_b}
$$

$$
\CL_{\mathrm{H}}=E_H \times Q_H=\frac{Q_H \times C l_{\mathrm{int}} \times f u_b}{Q_H+C l_{\mathrm{int}} \times f u_b}
$$

$$
\mathrm{F}_{\mathrm{H}}=\frac{Q_H}{Q_H+C l_{\mathrm{int}} \times f u_b}
$$

$$
\mathrm{CL_R} = \mathrm{RBF} \times \mathrm{E}=\mathrm{GFR} \times \frac{\mathrm{C}_{\text {in }}-\mathrm{C}_{\text {out }}}{\mathrm{C}_{\mathrm{in}}}
$$

$$
\CL_{\text {ren }}=\frac{\text { rate of excretion }}{\text { plasma concentration }}
$$

$$
\CL_{\text {ren }}=f u \times G F R+\left[\frac{\text { Rate of secretion }- \text { Rate of reabsorption }}{\text { Plasma concentration }}\right]
$$

$$
\mathrm{CL_R} = \frac{\text { Urine flow } \times \text { urine concentration }}{\text { Plasma concentration }}
$$

## k_e for aminoglycosides

$$
\mathrm{K}_{\mathrm{e}}=0.00293(\mathrm{CrCL})+0.014
$$

### Elimination rate constant

$$
k_{\mathrm{e}} =
  \frac{\CL}{\Vd} =
    \frac{
      \ln
      \left(
        \frac{\Conc_1}{\Conc_2}
      \right)
    }{
      \left(
        t_2 - t_1
      \right)
    } =
      \frac{
        \ln \Conc_1 - \ln \Conc_2
      }{
        \left(
          t_2 - t_1
        \right)
      }
$$

### Half-life

$$
t_{\textonehalf} =
  \frac{0.693 \times \mathrm{V_d}}{\CL}=\frac{\ln(2)}{k_{\mathrm{e}}}=\frac{0.693}{k_{\mathrm{e}}}
$$

::: {#refs}
:::
