---
title: "Gathering of Guilds"
subtitle: "Get in contact with the community"
description: "Directory of pharmacometrics societies, conferences, journals, and professional communities including ISoP, PAGE, and ACoP."
date: last-modified
---

:::{.callout-caution title="Under construction"}
:::

**Guild**:  
*An association of professionals for mutual aid and pursuit of a common goal.*


A directory of fellowships, societies, and forums where professionals meet and interact.
Find your chapter, share tales, and build alliances to sharpen your practice.

## Mailing Lists

* NMusers
  * A mailing list for professionals that use the NONMEM software.

## Communities

* International Society of Pharmacometrics ([ISoP](https://www.isop.org/home))
  * A non-profit organization dedicated to the advancement and promotion of pharmacometrics.
* [RedIF](https://www.redifar.org)
  * Ibero-American network in the field of pharmacometrics.
* [Pharmacometrics Africa](https://pmxafrica.org)
  * A non-profit company registered in South Africa with the goal to develop quantitative clinical pharmacology among African scientists, and more generally among pharmacometricians in low and middle income countries (LMIC).

## Conferences

*  Population Approach Group Europe ([PAGE](https://www.page-meeting.org)).
  * Annually in June
* The American Conference on Pharmacometrics ([ACoP](https://acop2025.eventscribe.net/index.asp))
  * Organized annually during the fall by ISoP.
* Population Approach Group of Australia and New Zealand ([PAGANZ](https://www.paganz.org))
* Stockholm-Uppsala Pharmacometrics ([SUP](https://www.sup-meeting.se))
  *  Bianually, alternately in Stockholm and Uppsala. One spring- and one fall-meeting.

## Journals

* Clinical Pharmacology & Therapeutics (CPT) <https://ascpt.onlinelibrary.wiley.com/journal/15326535>
* CPT: Pharmacometrics & Systems Pharmacology (CPT: PSP) <https://ascpt.onlinelibrary.wiley.com/journal/21638306>
* The Journal of Clinical Pharmacology (J Clin Pharm), <https://accp1.onlinelibrary.wiley.com/journal/15524604>
* Journal of Pharmacokinetics and Pharmacodynamics (JPKPD), <https://link.springer.com/journal/10928>
* Translational and Clinical Pharmacology (TCP), <https://tcpharm.org/>
* The AAPS Journal (AAPS), <https://link.springer.com/journal/12248>
* British Journal of Clinical Pharmacology (BJCP), <https://bpspubs.onlinelibrary.wiley.com/journal/13652125>
* Clinical Pharmacology in Drug Development (Clin Pharm Drug Dev), <https://accp1.onlinelibrary.wiley.com/journal/21607648>
* Clinical Pharmacokinetics (Clin PK), <https://link.springer.com/journal/40262>

## Websites

* <https://pmxrepo.com>
* <https://www.pkpd-info.com>
