---
title: "NMusers"
date: last-modified
---

The NONMEM Users Network (NMusers) is a mailing list for professionals that use the NONMEM software.

It is maintained by ICON Clinical Research LLC, and has been running since at least [1995](https://web.archive.org/web/20211122230941/https://www.cognigen.com/nonmem/nm/99oct191995.html).
The mail archive can be accessed here: [https://www.mail-archive.com/nmusers@globomaxnm.com/](https://www.mail-archive.com/nmusers@globomaxnm.com/).
It was previously hosted at `https://www.cognigen.com/nonmem/nm/`.

NMusers has an RSS-feed: [https://www.mail-archive.com/nmusers@globomaxnm.com/maillist.xml](https://www.mail-archive.com/nmusers@globomaxnm.com/maillist.xml)

## Subscribe

To **subscribe** to nmusers, send the following in the body (not the subject line) of an email message to [majordomo@globomaxnm.com](mailto:nmusers-request@iconplc.com):

```
subscribe nmusers
```

This will subscribe the account from which you send the message to the NMusers list.

If you wish to subscribe another address instead (such as a local redistribution list), you can use a command of the form:

```
subscribe nmusers other-address@your_site.your_net
```

Alternatively, requests to subscribe to the network can be sent to: [nmusers-request@iconplc.com](mailto:nmusers-request@iconplc.com).

Once subscribed, you may contribute to the discussion by emailing: [nmusers@globomaxnm.com](mailto:nmusers@globomaxnm.com).

## Unsubscribe

To **unsubscribe** from NMusers, send the following in the body (not the subject line) of an email message to [majordomo@globomaxnm.com](mailto:nmusers-request@iconplc.com):

```
unsubscribe nmusers
```

This will unsubscribe the account from which you send the message.
If you are subscribed with some other address, you'll have to send a command of the following form instead:

```
unsubscribe nmusers other-address@your_site.your_net
```

If you don't know what address you are subscribed with, you can send the following command to see who else is on the list (assuming that information isn't designated "private" by the owner of the list):

```
who nmusers
```

If you want to search non-private lists at this server, you can do that by sending a command like:

```
which string
```

This will return a list of all entries on all lists that contain "string".

## NMusers posting guidelines

1. Limit 40000 characters (including appending dialog history from previous responses, so truncate if it gets too long)
2. No attachments
3. Only text and links

[Reference 2019-03-15](https://www.mail-archive.com/nmusers@globomaxnm.com/msg07406.html)

## Searching NMusers

Searches span all archived messages in a particular mailing list.
More complex searches are supported through advanced query syntax.
Phrase search is supported.
So are fancy boolean operators like + - AND OR NOT ().
Finally, searches can be limited to a particular email field such as from, date, subject or message.
For example, one can find all messages from April 2002.
The sort order can be controlled by adding sort:newest or sort:oldest to your search string.

"battle royale"
+Jeff -Breidenbach -Marshall
(dualing OR dueling) AND banjos
from:"Mac Oglesby"
date:[20190101 TO 20191231] Breidenbach
date:202204*
help sort:newest
