---
title: "Meeting Best Practices"
date: "2026-02-22"
---

::: {.callout-caution title="Under construction"}
:::

## Meeting Energy Levels

* **A-Energy**: Focused, prepared, high-leverage meetings.
* **B/C-Energy**: Reactive, unclear, or unfocused meetings.

Aim to operate at **A-energy** by having clear strategies and ownership.

## Meeting Strategies

* What does a good agenda look like?
* Should agreed action points be emailed after

## Synthesis of meeting workflow (ref Alfred Sloan)

1. Send out invitation ~1 week in advance (No agenda = no meeting!)
    1. Announce purpose/topic and desired outcome.
    2. List agenda topics as questions.
    3. Compile and attach "reading guide"^[SE: "läsanvisning"].
    This is the context that everyone needs to be aware of for a meaningful discussion.
2. Have the meeting.
    1. Announce purpose/topic.
    2. Begin with 20--30 minutes of silent study time to ensure everyone has digested the reading guide.
    3. List agenda topics as questions (and **follow the agenda**)
        1. If it's **your meeting**: Present (do 90% of talking) and ask if there is anything that needs to be clarified
        2. If it's **[not]{.red-underline} your meeting**: Listen (do 10% of talking) and ask clarifying questions
    4. Anything we need to change/add?
    5. Review last meeting’s !/+/Δ
    6. Take notes on these things:
      * Decisions
      * Action-points (What should be done, by when, and who's responsible?)
        * MoSCoW
    7. 5 min to wrap up/summarize
        1. !: Align on decisions and action list.
        2. +: “What did we do well?”  
        3. Δ: “What do we want to do differently?”
    8. Decide **time of next meeting** (if needed)
3. Leave
4. **Immediately send an email** to attendees.
    1. Summarize discussion and conclusion.
    2. Spell out the **Action Memo** (deadlines and accountable persons)
    3. Inform on **next meeting** on the subject.
    4. Put **one attendee as sole recipient**.
    5. Send copy (CC) to all other attendees.

### My own take

* Write down what has been said/agreed upon to do
    * Only note decisions and actions
* Align on list at end of meeting
* Bring up the list first thing next meeting
* Write an Agenda, and follow it;
    * List agenda topics as questions
    * Cookie-cutter:
        * Last weeks action-list
        * This week
            * What do I want help with?
        * Next weeks action-list
            * Email it

## One-on-ones

* If you like structured agendas, then the employee should set the agenda.
    * A good practice is to have the employee send you the agenda in advance.
    * This will give her a chance to cancel the meeting if nothing is pressing.
    * It also makes clear that it is her meeting and will take as much or as little time as she needs.
* During the meeting, since it's the employee's meeting, the manager should do 10% of the talking and 90% of the listening.
    * Note that this is the opposite of most one-on-ones.

If you feel that you are floundering (as every student sometimes does), ask your advisor for extra meetings, send frequent email messages asking for pointers, or discuss your work with another trusted faculty member or student.

## Negotiation

* As low as possible: 65 –> 85 –> 95 –> 100
* As high as possible: 155 -> 120 -> 105 -> 100
* End on odd number

## Things to try for effective meetings

* Keep meetings small (6--8 key people).
* Standing meetings can reduce duration (increase effectiveness).
* Use AI transcription tools to quickly capture key meeting points and action items.
* Encourage discussion, debate, brainstorming, and questioning!
Be structured before (agenda) and after (memo) the meeting, but unstructured within the agenda.
* Implement [Maker-Manager schedules](https://paulgraham.com/makersschedule.html).
Managers thrive on 30-minute blocks for decisions.
Makers need 3--4 hour blocks for deep work-schedule afternoon meetings for makers to protect creative flow.
    * Maker: **deep work** in the AM (8--12), Manager: **meetings** in the PM (13--17).
    * Meetings mostly need to fall into a fairly narrow range of time slots to be reasonable for everyone.
    That means almost all meetings land in a 2 h time slot each day and the number than can be scheduled are limited so if it doesn't have to be a meeting, it isn't.
* Use the 4-bullet update:
    * Here's what you asked me to do...
    * Here's what I did...
    * Here are the current risk/blockers (if any)...
    * If given more time, I'd do this...

## Questions NGN (eNGiNe)

* Need-to-know: Answer will affect conclusion (Major objection, **always ask this**)
* Good-to-know: Answer could affect conclusion (Other concern, **ask if there is time**)
* Nice-to-know: Answer won't affect conclusion (**avoid asking this**)
