---
title: "Skin cancer"
---

## What is Skin Cancer?

There are three main types of skin cancer, depending on which cells have turned cancerous:

* Non-melanoma skin cancer (NMSC)
  * **Basal-cell carcinoma (BCC)**
    * Most common (~80% of skin cancers)
    * Grows slowly, rarely metastasizes
    * Low mortality
  * **Squamous-cell carcinoma (SCC)**
    * Medium frequency (~20% of skin cancers)
    * Can spread quickly and metastasize
    * Low mortality
    * Can be cured if caught early
* **Melanoma**
  * Least frequent (~1% of skin cancers)
  * Grows very fast, can spread
  * Highest mortality
  * Can be cured if caught early

### Non-melanoma skin cancer (NMSC)

#### BCC

Cancer of basal cells in the deepest skin layer (*stratum basale*, or *basal cell layer*).
Grows slowly, damages nearby tissues.

#### SCC

It is a cancer of keratinocytes ("squamous cells") in the next-to-deepest skin layer (*stratum spinosum*, or *squamous cell layer*).
These cells form on the surface of the skin, on the lining of hollow organs in the body, and on the lining of the respiratory and digestive tracts.
Also known as **epidermoid carcinoma**.

The cancer can be divided into types depending on the body location:

* Head and neck SCC (HNSCC)
* Cutaneous SCC (cSCC)
  * aka *squamous-cell carcinoma of the skin* or *squamous-cell skin cancer*
* Squamous-cell carcinoma of the thyroid (SCT)
  * aka *thyroid squamous-cell carcinoma*

### Melanoma

Cancer of melanocytes in e.g. the deepest skin layer, and also the eyes (i.e. wherever you have melanocytes).


## What are the symptoms?

### Risk factors

* Over exposure to sunlight/tanning beds
* A history of sunburns
* Fair skin & light eye/hair color
* Genetics
* Exposure to toxic chemicals
* Immunosuppresive drugs
* Arsenic exposure

## Diagnosis

* Physical examination
* Biopsy

### Grades and stages

The grade of a cancer tells you how much the cancer cells look like normal cells.

#### Number staging

The number stage of a cancer tells you how big it is and whether it has spread.
Stages range from 0 to 4.
Stages are defined differently if the cancer is on the eyelid.

BCC doesn't need staging because it's very rare for it to spread.

#### TNM staging for melanoma

TNM stands for Tumour, Node, Metastasis.

* (T)umour
  * 6 stages
  * Tumour thickness
* (N)ode
  * 4 stages
  * Describes whether cancer cells are in the nearby lymph nodes.
* (M)etastasis
  * 2 stages 
  * Describes whether the cancer has spread to a different part of the body.

## How can it be treated?

* Surgery
* Chemotherapy
* Radiation therapy
* Laser therapy
* Targeted drugs
* Checkpoint inhibitors (immunotherapy)
  * PD-1 inhibitor
    * Nivolumab (Opdivo)
    * Pembrolizumab (Keytruda)
    * Cemiplimab (Libtayo)
  * PD-L1 inhibitor
    * Atezolizumab (Tecentriq)
  * CTLA-4 inhibitor
    * Ipilimumab (Yervoy)

## References

* https://en.wikipedia.org/wiki/Squamous-cell_carcinoma
* https://www.youtube.com/watch?v=WXfb340OEeg
* https://en.wikipedia.org/wiki/Checkpoint_inhibitor
* https://www.cancerresearchuk.org/about-cancer/skin-cancer/stages-grades
* https://www.cancerresearchuk.org/about-cancer/melanoma/stages-types/tnm-staging
