---
title: "Augmented Renal Clearance (ARC)"
---

Augmented renal clearance (ARC) is a term used when a patients' creatinine clearance (CrCL) exceeds 130 mL/min/1.73m^2^.

Commonly, renal impairment is studied in drug development.
In contrast, ARC is when drug elimination is accelerated instead of reduced.
ARC is most common in critically ill young men.
Critical illness can caused by e.g. burns or infections.
Furthermore, critically ill patients often have rapidly fluctuating renal function.

Standard CrCL estimation equations like Cockgroft-Gault, MDRD, or CKD-EPI, are inaccurate at these high CrCL values.
Futhermore, standard CrCL estimation equations were developed for steady-state conditions.

In a study by Andrew Udy et al., 85% of patients with traumatic brain injury who needed saline infusion and vasopressor agents to maintain cerebral perfusion pressure had ARC.
Using the timed urinary creatinine clearance method to measure GFR, ARC has been observed in burn patients, those with sepsis, post-surgery, and in ICU settings.
Brown et al. recorded a creatinine clearance of 190 ml/min/1.73 m² in critically ill postoperative patients.
More recently, Fuster-Lluch et al. reported an ARC incidence of 17.9% in postoperative and polytrauma patients.
These patients were younger, had lower APACHE II scores, higher diastolic blood pressures, and higher urine output on the first morning in the ICU.

Cytokine release from acute injury, the body's immune and inflammatory responses to trauma, and aggressive fluid resuscitation may all contribute to increased organ blood flow and enhanced excretory function.
Understanding ARC is crucial, as it impacts the dosing of renally excreted drugs, potentially making standard dosing regimens insufficient for patients with ARC.
Baptista et al. found that commonly used GFR estimation equations underestimated creatinine clearance in patients with ARC.

Here are the key challenges in estimating GFR in ICU patients:

1. Rapidly changing renal hemodynamics
2. Risk of both overdosing and underdosing due to inaccurate GFR estimates
3. Constantly fluctuating patient volume status
4. ARC is often overlooked in GFR calculations, leading to inadequate drug dosing
5. Common creatinine-based equations are unreliable in critical care settings, and ideal methods like inulin clearance are impractical in the ICU.

## Ways to deal with ARC in PK modeling

Introduce a scalar above 130 mL/min.
The idea is that this will estimate, and correct for, the bias of estimating equations in ARC.
Ofcourse, this assumes that the bias is linear.

# References

* Kristoffersson et al. (2020) https://doi.org/10.1016/j.cmi.2020.03.016
* Atkinson (2018) https://doi.org/10.12793/tcp.2018.26.3.111
* Sunder et al. (2014) https://doi.org/10.1186/2052-0492-2-31
