---
title: "PKPD or Exposure-Response modeling"
date: last-modified
---

::: {.callout-caution title="Under construction"}
:::

## PKPD modeling strategies

* Assume a PK model
  * Estimate PK and PD parameters in a simultaneous fit (SIM)
  * Estimate PK parameters first and then fit PD
    * Condition on individual PK parameter estimates
      * Assume no error in parameters (IPP = Individual PK Parameters)
      * Account for error in parameters (IPPSE = Individual PK Parameters Standard Error) [@lacroixEvaluationIPPSEAlternative2012]
    * Fix population PK parameters
      * Include individual PK data (PPP&D = Population PK Parameters & Data)
      * Don’t include individual PK data (PPP = Population PK Parameters)

Abbreviations in Zhang et al 2003 [@zhangSimultaneousVsSequential2003]  

## Binary

### Logistic regression

Logistic regression is used to model binary data.
It is often used for eg E-R or dropout modeling.

E-R relationships of dichotomous endpoints based on logistic regression can be reliably assessed even in the presence of high shrinkage in the pharmacokinetic exposure metric [1,2].

::: {.callout-note}

# Which exposure metric should be used in E-R?

Ususally, just try all of them (e.g., C~avg~, C~trough~, C~max~), and choose the best one (lowest AIC).
They are most of the time highly correlated (>0.95), i.e., any of them can be used.

:::

## Ordinal data

* Composite scores
  * IRT
  * BI
  * PO

## References

1. PAGE 31 (2023) Abstr 10663 [https://www.page-meeting.org/?abstract=10663]
2. PAGE 32 (2024) Abstr 11183 [https://www.page-meeting.org/?abstract=11183]

::: {#refs}
:::
