---
title: "NONMEM troubleshooting"
code-overflow: scroll
date: last-modified
---

::: {.callout-caution title="Under construction"}
:::

## Troubleshooting

<https://pmxrepo.com>

### EXIT OCCURS DURING SEARCH FOR ETA

```nmtran
0PRED EXIT CODE = 1
0INDIVIDUAL NO.       4   ID= 4.00000000000000E+00   (WITHIN-INDIVIDUAL) DATA 
REC NO.   2
THETA=
  1.00E-03   5.00E-01   1.00E+01   1.00E+01   1.00E-01   1.00E+01   1.00E+00
OCCURS DURING SEARCH FOR ETA AT INITIAL VALUE, ETA=0
F OR DERIVATIVE RETURNED BY PRED IS INFINITE (INF) OR NOT A NUMBER (NAN).
 Elapsed estimation time in seconds:     0.00
```

This is a generic error message, nothing informative except indicates that there are some numerical problems.
Often this is related to the outliers, so it helps to clean the data.

Things to try:

* Change ADVAN (6 to 13, if this is differential equations model).
* Change `TOL` in `$SUBROUTINES` record.
* Change `SIGL` and `NSIG` in `$ESTIMATION`.
* Change initial estimates
  * To something else within a realistic range.
  * To the values of the previous model.
  * If this is a complex model, try to start with something simpler, like linear, and use the output as initial estimates, and also look for outliers.
  * Increase initial estimate of RUV.
* Sometimes `MCETA=1000` in `$ESTIMATION` records helps with this message.
* Add IIV on RUV.

([Credit: Leonid Gibiansky](https://www.mail-archive.com/nmusers@globomaxnm.com/msg08915.html))

::: {.callout-note title="Terminology"}
* Use "Disease modifying" instead of "protective" (Credit: Mats Karlsson)
* Time varying covariate: Specify as "regressor".
:::

## References

::: {#refs}
:::
