---
title: "Goodness-of-fit for continuous data"
date: last-modified
---

:::{.callout-caution title="Under construction"}
:::

The graphs are broadly separated into two categories: prediction-based (basic) and simulation-based tools.

| Plot | Model assumption tested | What to evaluate | Model impact |
| :--- | :--- | :--- | :--- |
| **Exploratory plots** |  |  |  |
| Time course of HR stratified by dose | No drug effect on HR | Consistency of change from baseline HR ΔHR with time, dose and treatment | If dose- or concentration-dependent effects on HR are observed, the relationship between QT and RR may differ between on- and off-treatment, impacting the QT correction differently between the two conditions <br> This could potentially violate the assumption that the applied QTc correction is an adequate heart rate correction method |
| QTc versus RR intervals | QTc is independent of HR for drug-free and/or placebo treatments | Linear regression line should show the lack of relationship between QTc and RR intervals <br> Range of HR are similar off- and on-drug | Individual correction factor is potentially poorly estimated due to narrow range of RR intervals within each subject which could bias the C-QTc model |
| Time course of mean concentrations and mean ΔQTc, ΔΔQTc intervals | Explore direct effect assumption <br> Evaluate PK/PD hysteresis | Shape of PK- and QTc-time profiles, e.g., time course of effect, time of peak, return to baseline <br> Magnitude of variability in PK and QTc | High inter-subject variability in ΔQTc can mask signal in mean curves-this is important in small-sized studies |
| C-ΔQTc | Evaluate linearity and heterogeneity assumptions between exposure and QTc across doses and studies | Shape of C-QTc relationship <br> Magnitude of ΔQTc over observed concentration range <br> Concentration range covers worse case clinical exposure scenario | Model-independent observations are not corrected for covariates and might therefore not appear to match model prediction <br> Confounding factors not accounted for Heterogeneity between doses/trials |

## Prediction-based evaluation

### Population-based graphs

| Plot                      | What is evaluated?      | What to evaluate | Model impact |
| :------------------------ | :---------------------- | :--------------- | :----------- |
| **DV vs. PRED**           | **Structural model**, **RUV model** or **IIV model** | Trends |
| **CWRES vs (TIME, PRED)** |                         | Trends may suggest a modification of **structural model**, **RUV model**, or **IIV model**. Trends by conditioning on covariates suggest including covariates. | |
| **CWRES vs COV**          |                         | Trends suggest **including covariates** or changing the **covariate model**. | |

: Various evaluation graphs in nonlinear mixed effect model aand proposal for a core set of evaluation graphs {#tbl-gof-pop tbl-colwidths="[25, 75]"}

### Individual-based graphs

| Graphs | What does it assess? |
| :--- | :--- |
| Individual fits: **(DV, PRED, IPRED) vs TIME** | Expect evenly distributed observation around the individual predicted curve, not spot-on predictions (indication of overfit). This diagnostic is not useful for sparse data. |
| **DV vs IPRED** | Only evaluates **strutural model and RUV**, not IIV. |
| **IWRES vs (TIME, IPRED)** | **Evaluates RUV**. A cone-shaped graph of IWRES vs IPRED suggests a change in the error model. |
| **ETAx vs ETAy** | Prefer random sampling of ETAs from posterior distribution. Correlation between EBE suggests including **correlation between random effects** unless data are sparse. |
| **ETA vs COV** | Trends between EBE and covariates suggest **including covariates** or changing the **covariate model**. |

: Various evaluation graphs in nonlinear mixed effect model aand proposal for a core set of evaluation graphs {#tbl-gof-ind tbl-colwidths="[25, 75]"}

## Simulation-based evaluation

(pc)VPC: Trends may suggest a modification of the structural model, the residual error model, or the parameter variability model.
Trends when conditioning on covariates suggest including covariates or changing the covariate model.

### Explanation of pcVPC

A Prediction-Corrected Visual Predictive Check (pcVPC) addresses limitations of conventional VPCs by **correcting for predictable sources of variability**, allowing clearer detection of model misspecification.

More specifically, a pcVPC **divides (normalizes) the dependent variable** by the **population prediction** for each bin.
This correction removes the influence of variability due to independent variables.

This is especially important when **data includes large variations in covariates** (e.g., dose), or when adaptive dosing strategies are applied.
