#!/bin/bash

# Fix duplicate canonical tags in generated HTML files
# This script removes the first (incorrect) canonical tag that points to the homepage,
# keeping only the second (correct) page-specific canonical tag generated by Quarto

echo "Fixing duplicate canonical tags..."

# Find all HTML files in _site directory
find _site -name "*.html" -type f | while read -r file; do
  # Check if file has duplicate canonical tags
  canonical_count=$(grep -c '<link rel="canonical"' "$file" 2>/dev/null || echo "0")

  if [ "$canonical_count" -gt "1" ]; then
    echo "  Fixing $file (found $canonical_count canonical tags)"

    # Use sed to remove the first canonical tag (the one pointing to homepage)
    # This preserves the second canonical tag which has the correct page-specific URL
    sed -i.bak '0,/<link rel="canonical" href="https:\/\/vrognas\.com\/">/{/<link rel="canonical" href="https:\/\/vrognas\.com\/">/d;}' "$file"

    # Remove backup file
    rm "${file}.bak"
  fi
done

echo "Done fixing canonical tags!"
