---
title: "Disease primer: Skin cancer"
---

There are three main types of skin cancer, depending on which cells have turned cancerous:

* Non-melanoma skin cancer (NMSC)
  * Basal-cell carcinoma (BCC)
    * Most common (~80% of skin cancers)
    * Rarely metastasizes
    * Low mortality
  * Squamous-cell carcinoma (SCC)
    * Medium frequency (~20% of skin cancers)
    * Can spread quickly and metastasize
    * Low mortality
    * Can be cured if caught early
* Melanoma
  * Least frequent (~1% of skin cancers)
  * Grows very fast, can spread
  * Highest mortality
  * Can be cured if caught early

### Non-melanoma skin cancer (NMSC)

#### BCC

Grows slowly, damages nearby tissues.

#### SCC

It is a cancer of *squamous cells*.
These cells form on the surface of the skin, on the lining of hollow organs in the body, and on the lining of the respiratory and digestive tracts.
Also known as **epidermoid carcinoma**.

The cancer can be divided into types depending on the body location:

* Head and neck SCC (HNSCC)
* Cutaneous SCC (cSCC)
  * aka *squamous-cell carcinoma of the skin* or *squamous-cell skin cancer*
* Squamous-cell carcinoma of the thyroid (SCT)
  * aka *thyroid squamous-cell carcinoma*

### Melanoma

## Typical patient

### Risk factors

* Over exposure to sunlight
* A history of sunburns
* Fair skin

## Clinical diagnostics

* Physical examination
* Biopsy

NMSC stages range from 0 to 4.

Melanoma stages range from 0 to 4.

## Treatment

* Surgery
* Chemotherapy
* Radiation therapy
* Laser therapy
* Drugs
* Immunotherapy
  * Ipilimumab
  * Pembrolizumab
  * Nivolumab

## References

* https://en.wikipedia.org/wiki/Squamous-cell_carcinoma
