---
title: "Concentration-QT (C-QT) modeling"
date: last-modified
---

::: {.callout-caution title="Under construction"}
:::

## Data

The default dependent variable (`DV`) is ΔQTcF.

## Modeling

The pre-speciﬁed linear mixed effect (LME) C-QTc model (@eq-lme) is used as the primary analysis.

$$
\Delta \mathrm{QTc}_{i j k} =
  \left(
    \theta_1 + \eta_{1, i}
  \right) +
  \theta_2 \mathrm{TRT}_j +
  \left(
    \theta_3 + \eta_{3, i}
  \right) C_{i j k} +
  \theta_4 \mathrm{TIME}_j +
  \theta_5
  \left(
    \mathrm{QTc}_{i, j=0} - \overline{\mathrm{QTc}_0}
  \right)
$$ {#eq-lme}

@garnettScientificWhitePaper2018

* $\theta_1$: Population mean intercept wihtout drug effect
* $\theta_2$: Treatment effect (1=drug, 0=placebo)
* $\theta_3$: Slope (Continuous covariate. Parent or metabolite concentrations)
* $\theta_4$: Mean QTc change from baseline at TIME = *k* for placebo
* $\theta_5$: Baseline QTc effect
* $C_{i j k}$: Concentration for subject i in treatment j and time k;
* $\mathrm{QTc}_{i, j=0}$: Baseline QTc
* $\overline{\mathrm{QTc}_0}$: Mean of all the baselines

## Evaluation

| Plot | Model assumption tested | What to evaluate | Model impact |
| :--- | :--- | :--- | :--- |
| **Exploratory plots** |  |  |  |
| Time course of HR stratified by dose | No drug effect on HR | Consistency of change from baseline HR ΔHR with time, dose and treatment | If dose- or concentration-dependent effects on HR are observed, the relationship between QT and RR may differ between on- and off-treatment, impacting the QT correction differently between the two conditions <br> This could potentially violate the assumption that the applied QTc correction is an adequate heart rate correction method |
| QTc versus RR intervals | QTc is independent of HR for drug-free and/or placebo treatments | Linear regression line should show the lack of relationship between QTc and RR intervals <br> Range of HR are similar off- and on-drug | Individual correction factor is potentially poorly estimated due to narrow range of RR intervals within each subject which could bias the C-QTc model |
| Time course of mean concentrations and mean ΔQTc, ΔΔQTc intervals | Explore direct effect assumption <br> Evaluate PK/PD hysteresis | Shape of PK- and QTc-time profiles, e.g., time course of effect, time of peak, return to baseline <br> Magnitude of variability in PK and QTc | High inter-subject variability in ΔQTc can mask signal in mean curves-this is important in small-sized studies |
| C-ΔQTc | Evaluate linearity and heterogeneity assumptions between exposure and QTc across doses and studies | Shape of C-QTc relationship <br> Magnitude of ΔQTc over observed concentration range <br> Concentration range covers worse case clinical exposure scenario | Model-independent observations are not corrected for covariates and might therefore not appear to match model prediction <br> Confounding factors not accounted for Heterogeneity between doses/trials |
| **Goodness of fit plots** |  |  |  |
| Model predicted versus observed ΔQTc | Model specification is adequate. | Model and observed values should fall around the line of unity without evidence of systematic bias. Loess smooth line with 95% CI should include the unity line over range of values | Systematic bias indicates model misspecification. For example, model predictions will be negatively biased at high values when PK/PD hysteresis is ignored and model predictions will be positively biased at high values when a linear model is applied to nonlinear data |
| Quantile-Quantile plot of residuals | Residuals follow normal distribution with mean of zero | Residuals should fall on the line of unity | Heavy tails indicate model misspecification. The plot does not indicate source of misspecification |
| Concentrations versus residuals <br> Baseline QTc versus residuals | Model covariates are adequate | Residuals should be randomly scattered around zero <br> The 95% CI of the loess line should include zero | Bias in residuals indicates model misspecification. A residual plot should be made for each model parameter |
| Time versus residuals |  |  |  |
| Active treatment versus residuals |  |  |  |
| Quantiles of concentrations and ΔQTc overlaid with slope of final model | Drug effect model is adequate | The concentration-QTc relationship obtained from final model should describe the observed data | Any systematic differences between the modeled versus observed data indicates model misspecification |

## References

::: {#refs}
:::
