---
title: "Time-to-event analysis"
---
Models for time to event^[Events are things that happen at a particular time.] provide the link between standard PKPD models, disease progression, and clinical outcome events.
The biological basis for events may be expressed quantitatively in terms of a hazard function.

## The Hazard

Hazards, exactly like elimination rate constants, have units of 1/time.

This simple product of hazard h and time t to predict the survivor function only works when the hazard is constant.

More generally, the survivor function is calculated from the integral of the hazard with respect to time—a quantity called the cumulative hazard (cumhaz).

When the exact time of the event is observed, the likelihood is the product of the survivor function and the hazard at that time.

When the hazard is constant, the shape of the pdf is exponential.

In real life, the time of zero is at entry into a clinical study, and it is unrealistic to imagine that at exactly that instant, the hazard of an event such as death plunges to zero.

## TTE models

There are different types of methods for analyzing time-to-event (TTE) data.
The Cox model is the most widely used survival model in the health sciences, but it is not the only model available.
In pharmacometrics we often use *parametric models*.
A parametric survival model is one in which survival time (the outcome) is assumed to follow a known distribution.
Distributions commonly used for parametric survival models are:

* Weibull
* Exponential
* Log-logistic
* Lognormal
* Generalized gamma

::: {.callout-note}
The Cox proportional hazards model, by contrast, is not a fully parametric model. Rather it is a semi-parametric model because even if the regression parameters (the betas) are known, the distribution of the outcome remains unknown. The baseline survival (or hazard) function is not specified in a Cox model.
:::

### Proportional hazard (PH)

### Accelerated failure time (AFT)

Many parametric models are acceleration failure time (AFT) models in which survival time is modeled as a function of predictor variables.

## Landmark analysis

Landmark analysis is used to **correct for immortal time bias**.
This bias is inherent in the analysis of time-to-event outcome between **groups determined during study follow-up**.^[Dafni U. Landmark Analysis at the 25-Year Landmark Point. Circ Cardiovasc Qual Outcomes. 2011;4:363-371.]
This method was originally proposed to evaluate the association between treatment response and survival^[Anderson JR, Cain KC, Gelber RD. Analysis of survival by tumor response. J Clin Oncol. 1983;1:710–719.], or to allow for groupings based on any covariate whose value is not known at baseline.

Looking at @fig-landmark-1, an incorrect approach would be to classify Subject 1 as a non-responder and Subjects 2 and 3 as responders (as is the case at six months) and then compare the survival between these two groups.

![
  Response times for three hypothetical subjects.
  Time of response indicated with a square.
  Dashed lines represent time the subject has not responded to treatment;
  solid lines denote the time during which the subject has responded.
](images/landmark-1.png){#fig-landmark-1}

That is, "responders" and "nonresponders" are compared with regard to survival from the start of the study.
This assumes that Subjects 2 and 3 responded to treatment immediately.
However, **response status (group assignment) is unknown at baseline**.
That is, all subjects begin the study as non-responders and do not become responders until later.
**Responders are (by definition) guaranteed to survive at least until the time of response.**
Classifying groups in this way leads to **immortal time bias.**

### How to perform landmark analysis

The landmark method analyzes survival based on patient response at a fixed time after starting therapy, called the "landmark".
Any subjects who were lost to follow-up or died prior to this time point are excluded from further analysis.
Subjects are then grouped by their response status at the landmark.
Any subject who has not responded by the landmark time is classiﬁed as a non-responder, even if that subject later responds to treatment.
This approach estimates survival from the landmark, based on response status at that time.

It is commonly used in clinical trials to classify patients into **groups based on events during follow-up**, such as receiving a treatment, stopping medication, or switching treatment.

Two examples of this process:

* In @fig-landmark-2, a landmark time of two months post-treatment is chosen.
Subjects 1 and 2 are then classiﬁed as non-responders because neither subject has responded to treatment at that time.
Note that even though Subject 2 will later go on to respond to treatment, to avoid the immortal time bias, Subject 2 must be considered to be a non-responder due to his or her status at the landmark time.
Subject 3 responded to treatment prior to the landmark time and is thus classiﬁed as a responder.

![
  Classiﬁcation of hypothetical subjects according to status at landmark.
  Subjects are classiﬁed as either responders (red) or non-responders (blue) based on their status at the landmark time.
](images/landmark-2.png){#fig-landmark-2}

* As can be seen in @fig-landmark-3, selecting a different landmark time (here, four months post-treatment) may change the classiﬁcation of some subjects.
In this example, the later landmark allows Subject 2 enough time to respond to treatment, leading to this subject being placed in the responder group.

![
  Classiﬁcation of hypothetical subjects according to status at landmark.
  Subjects are classiﬁed as either responders (red) or non-responders (blue) based on their status at the landmark time.
](images/landmark-3.png){#fig-landmark-3}

Once the landmark has been chosen, any ineligible subjects have been excluded, and subjects have been classiﬁed according to their status at the landmark time, the usual survival analysis methods are applied.
The results of these methods are interpreted as usual, with the important caveat that conclusions are only generalizable to subjects who have survived until the landmark time.

To avoid bias, the landmark should be chosen before data analysis begins and ideally should correspond to a clinically meaningful period of time.
When the choice of landmark time is not obvious, the data should be analyzed using multiple landmark times in order to determine the sensitivity of the ﬁndings to the choice of landmark.

**An alternative to landmark analysis is to allow the value of the covariate indicating treatment response to vary over time.
This is doable using pharmacometric software such as NONMEM.
This does not require any subjects or events to be excluded from the analysis.
Is also avoids both the problem of selecting a landmark time and any misclassiﬁcation errors.
**

## References

* [Morgan CJ (2019). Landmark analysis: A primer.](doi:10.1007/s12350-019-01624-z)