---
title: "Email like a Boss"
date: last-modified
---

* Remove all notifications about new email.
  * You're not the President of the United States who needs to react to a nuclear threat.
  Emails/calls can always wait a few minutes.
* Agree on email response times (e.g., one/two business days)
* Never send emails outside office hours
  * Many modern email clients now have a "Send Later" functionality.
  Use it if you work ouside office hours.

## Read email in batches

* Schedule reading at least once per day, what works for you.
  * Expect ~30 sec to process every email (i.e., decide what to do with it, see below).
* Strive for "inbox zero"^[an empty inbox]---every day.
  * The inbox is for emails you have have decided what to do with yet.
* If you open an email---make a decision.
  * Action required (takes ≤2 min^[or other amount that works for you])? **Do it now**
  * Action required (takes >2 min)? **Schedule it**
  * Action required (but waiting for something/someone)? **Set a reminder**
  * Action not required? **Archive**
    * Other emails go into the archive.
    Also all emails that required action go into the archive after action is taken.
    * I've found that just archiving all emails is more efficient than spending time to sort them into subfolder.
    When you want a certain email, just search for it.
* In general: Do not answer mails that you've been CC'ed on.
* (Almost) never use "Reply All".
  * Want fewer emails? Send fewer emails.

## Write your email backwards

> Sorry I'm writing a long email, but I did not have time to write a short one.

1. Start with **jotting down** what you want to say in the body of the email.
If it is a really short message, consider using only the subject line, ending it with "EOM" (End of Message).
* Keep email short, clear, and on topic.
  * [ChatGPT](chat.openai.com) can help to make emails more coherent, consise, and to the point.
  * A good rule of thumb is to aim for max 5 sentences.
  If it is longer than that, email is probably not the right way to communicate.
  * AVOID CAPITAL LETTERS
  * Avoid irony and sarcasm
  * Do not use more than one exclamation mark!!!!!!!
  Same goes for the question mark????
  And dots........ (what you want here is the *ellipsis* "...").
  * Mind your language.
    * Avoid profanity.
    * Be polite, and not overly apologetic (see @tbl-email).
    * Use abbreviations, symbols, and emojis sparingly.

:::{.callout-note title="Note on emojis"}
Emojis are meant to convey emotion in writing.
Correctly used, they are irreplaceable in making sure your message is read in the intended tone of voice, even in professional email.
:::

### Corporate lingo

| Lingo             | Try this |
| :---------------- | :------- |
| Alignment         |          |
| Circle back       |          |
| Low-hanging fruit |          |
| Bandwidth         |          |
| Resources         |          |
| Synergy           |          |
| Resources         |          |
| EOB/EOD           | Say the clock time |

: Corporate lingo {#tbl-corporate-lingo}

### Be assertive

| What you mean                          | Instead of saying...               | Try saying this instead                    |
| :------------------------------------- | :--------------------------------- | :----------------------------------------- |
| I know your time is valuable           | Sorry to bother you                | Appreciate you making time for this        |
| That might have been unclear           | Sorry for the confusion            | Let me clarify that for you                |
| I'm learning and want to get it right  | Sorry for asking so many questions | I value your insight as I learn more       |
| I want to contribute thoughtfully      | Sorry for jumping in               | May I offer a thought here?                |
| I can explain this better              | Sorry if that didn’t make sense    | Let me rephrase that to be clearer         |
| I need some guidance                   | Sorry, I’m not sure how to do this | Could you walk me through the next step?   |
| I need to express something            | Sorry for venting                  | Thank you for listening                    |
| I appreciate your attention            | Sorry for taking up your time      | Grateful for the opportunity to share this |
| I took a while, but you can deal       | Sorry for the delay                | Thanks for your patience                   |
| My schedule matters too                | What works best for you?           | Could you do __:__?                        |
| Yeah, you're welcome                   | No problem / No worries!           | Always happy to help!                      |
| I know what I’m doing                  | I think maybe we should __         | It’d be best if we __                      |
| Wording this is hard                   | *Rewriting email for 40 minutes*   | It’d be easier to discuss in person        |
| Do you get it?                         | Hopefully that makes sense?        | Let me know if you have questions          |
| Where the heck are we on this?         | Just wanted to check in            | When can I expect an update?               |
| I made a small error                   | Sorry I missed that                | Nice catch! I've updated it now. Thanks for letting me know! |
| I have an appointment                  | Could I possibly leave early?      | I will need to leave for ___ at ___        |

: Assertive communication {#tbl-assertive-communication}

:::{.callout-note title="Note on attachments"}
Prefer links to secure servers over attaching files.
:::

2. Next, **summarize** message and action-points in the beginning of an email.
3. Write an accurate (and short) **subject line**.
* Consider starting your subject lines with a word such as:
  * Action:
  * Info/FYI:
  * Question:
  * Feedback:
* Does the email contain links to draft working material? Write "draft" in the subject.
* Avoid confidential info on the subject line.

:::{.callout-tip}
# Stick to one topic

**New topic? New email.**

Do *not* take the opportunity to discuss a little bit of this and that.
:::

4. **Read through** the email once (yes, once is enough), and correct any obvious mistakes.
5. **Add the recipients** after you've written the email, that way you don't accidentally send an unfinished email.
6. **Hit send!** (or "Send Later" if you work outside office hours)

* CC can be viewed as ”For your information”
  * If you put someone in CC, don't expect them to answer. It is either not actionable for them, or not directly related to them.
* Don't overuse CC. Everybody does not need to know everything.

:::{.callout-tip}
# CC & BCC

**CC = "carbon copy".**
Back in the days before internet and email, in order to create a copy of the letter you were writing, you had to place carbon paper between the one you were writing on and the paper that was going to be your copy.

**BCC = "blind carbon copy."**
It’s called *blind* carbon copy because the other recipients won't be able to see that someone else has been sent a copy of the email.
While you can see a list of recipients when CC is used, that's not the case with BCC.
No one ever sees the BCC list.
A BCC can reply to the sender, but other recipients can't send to BCC recipient with "reply all".
:::

## Do not use email for these situations

* When you require a quick answer (call them or go face-to-face instead)
* When you want to give negative feedback (go face-to-face instead)
* When you need to deliver bad news (go face-to-face instead)
* When you are emotional (write a draft and send later instead)
