---
title: "Wisdom Notes"
date: "2026-09-20"
draft: true
---

::: {.callout-caution title="Under construction"}
:::

From my post-it notes


## Vision

* She isn't sick, she's a *dancer*
* Employee = A pawn in someone elses game of chess.
* Memento mori
* You are important
* "Framtida du" är **du**, **inte** en främling.
**Du** tar alla konsekvenser.
* We will not hit break-through by christmas; but if we *keep pushing*, we **will** eventually hit **break-through**.
* Productivity distribution: 1% Pareto winner-takes-all
* What makes my heart sing?

## Self-mgmt strat/tacs

* State-Management (tony robbins)
* If what you are doing doesn't work; do something else.
* What **not** to do
* As if you were a person that you were taking care of
  * Good boss to good employee
* Focus on **showing up**, *then* focus on *how* you show up.
* The good shit sticks
* Best people on best opportunities, not problems.
  * Opportunities up -> Great
  * Problems down -> Good
* People - Thought - Action
* Don't ask your leader what you should do; tell them what you are *going* to do

* Check my ego.
  * Let go of ego; truly.
  * Inse att du ej är något; skit i image; jobba för bättre.
* Bring your best self

* Do
  * Focus on mission; get it **Done**; figure it out; take ownership --- solve it
  * Do the movements
  * Jag är en sån som *gör* saker
  * Inget händer förrän någon säljer något.
* Don't sell to people that don't *want* the product

* Fanatic Discipline - Productive Paranoia - Empirical Creativity

* Detach and lead
* **Be** the person you want to be
  * KBT?

* Hearty in my approbation & lavish in my praise

* A man convinced against his will, is of the same opinion still

* Förebild; Build **trust**
* Leaders prepare their troops!
  * Soldiers given a task they haven't been prepared for, loose confidence in themselves, and fatally in their leaders.
* Set goals that make you jump out of bed in the morning.
* Lead up and down

* Utsänd för att träna på
* Every man I meet is my superior in some way; in that, I learn, of him. - Emerson
* If I have a problem iwth someone/something, it is *my* problem
* See things *as they are* (not worse than they are).
Then see things *better than they are*, and develop a plan to get there.
* Decision time: 1/3 your analysis; 2/3 subordinates analysis.
**Use all time** -> 40--70% of information.

* Do not react; but **respond**
